function httpdcount {
    ps aux | grep httpd | grep -v grep | wc -l
}

alias c='clear'
alias ls='ls -G'
alias ll='ls -la'
alias ps='ps ax'

export PS1='\[\033[01;32m\]\h\[\033[01;34m\] \w\[\033[31m\]$(__git_ps1 "(%s)") \[\033[01;34m\]$\[\033[00m\] '

export GREP_OPTIONS="--colour=auto"
export EDITOR=mcedit

export HISTIGNORE='&:ls:exit'
export HISTSIZE=100000
export HISTFILESIZE=409600

export SUDOLESS=yay

source ~/.git-completion.sh

