#!/usr/bin/ruby
require 'irb/completion'
require 'irb/ext/save-history'

IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:AUTO_INDENT] = true

Hirb.disable if defined?(Hirb)

class Object
  # Return only the methods not present on basic objects
  def interesting_methods
    (self.methods - Object.new.methods).sort
  end
end

def os_copy(str)
  IO.popen('pbcopy', 'w') { |f| f << str.to_s }
end

def os_paste
  `pbpaste`
end

def ep
  eval(paste)
end
