set nocompatible               " use vim features

syntax on
filetype on
filetype indent on
filetype plugin on

set foldmethod=marker " | syntax
set foldlevelstart=1
set foldnestmax=5
set foldclose=all

set nobackup                   " no backup
set nowritebackup              " no backup during edit session

set backspace=indent,eol,start " backspace over everything

set tabstop=2     " size of a tab
set shiftwidth=2  " size for auto/smartindent
set softtabstop=2 " a tab is this size
set expandtab     " spaces not tabs
set smartindent   " indents for you
set smarttab      " tabs at start of lines
set autoindent    " always set autoindenting on
set pastetoggle=<D-e>

function! GitBranch()
    let branch = system("git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* //'")
    if branch != ''
        return "(" . substitute(branch, '\n', '', 'g') . ")"
    en
    return ''
endfunction

function! RvmOrFiletype()
  if &filetype=='ruby'
    let status = ''
    if !empty($rvm_path)
      let status = $GEM_PATH
      let status = "ruby/" . substitute(status, '.*/', '', '')
    endif
    return status
  else
    return strlen(&filetype)?&filetype:'none'
  endif
endfunction

" set list
set encoding=utf-8
set showcmd
set timeoutlen=50
set wildmenu

set laststatus=2  " always show status line
set statusline=[%{getcwd()}\%{GitBranch()}\]\ %f\ %2*%m\ %1*%h%r%=%{strlen(RvmOrFiletype())?RvmOrFiletype():'none'}\ 0x%B\ %12.(%c:%l/%L%)

set so=7       " 7 lines when scrolling vertically
set ffs=unix   " eol
set showmatch  " show matching bracket

set noerrorbells
set novisualbell
set vb t_vb=   " no bells
set modeline   " show current mode
set incsearch  " do incremental search
set history=50 " keep 50 lines in history
"set nowrap     " no wrap
set hlsearch   " highlight search word
set ruler

if has("gui_running")
  "colors molokai
  colors spring
  set guifont=Monaco:h11
  set guioptions-=T
  set guioptions-=r
  " nmap <silent> <> :CommandT<CR>
  " full screen mode
  set fuoptions=maxhorz,maxvert
  nmap <D-CR> :set invfu<CR>

  " C-# switches to tab
  "nmap <d-1> 1gt
  "nmap <d-2> 2gt
  "nmap <d-3> 3gt
  "nmap <d-4> 4gt
  "nmap <d-5> 5gt
  "nmap <d-6> 6gt
  "nmap <d-7> 7gt
  "nmap <d-8> 8gt
  "nmap <d-9> 9gt
endif

hi Todo guifg=#FF0000 guibg=#FF7F50
hi TODO guifg=#FF0000 guibg=#FF7F50
hi XXX  guifg=#FF0000 guibg=#FF7F50

autocmd BufWritePre *.rb :%s/\s\+$//e
autocmd BufWritePre *.c :%s/\s\+$//e
au BufRead,BufNewFile *.scss  set filetype=scss
au BufRead,BufNewFile *.scss  set filetype=eruby

" w!! when you forgot sudo
cmap w!! %!sudo tee > /dev/null %

