set nocompatible               " use vim features
" set foldmethod=syntax
set foldmethod=marker
set foldlevelstart=1
set foldnestmax=5
set foldclose=all
set nobackup                   " no backup
set nowritebackup              " no backup during edit session
set backspace=indent,eol,start " backspace over everything
set tabstop=2     " size of a tab
set shiftwidth=2  " size for auto/smartindent
set softtabstop=2 " a tab is this size
set expandtab     " spaces not tabs
set smartindent   " indents for you
set smarttab      " tabs at start of lines
set autoindent    " always set autoindenting on
set laststatus=2  " always show status line
set pastetoggle=<D-e>

" set list
set encoding=utf-8
set showcmd
set timeoutlen=50
set wildmenu
if &statusline == ''
  set statusline=%f\ %2*%m\ %1*%h%r%=[%{&encoding}\ %{&fileformat}\ %{strlen(&ft)?&ft:'none'}\ %{getfperm(@%)}]\ 0x%B\ %12.(%c:%l/%L%)
endif

set so=7 " 7 lines when scrolling vertically
set ffs=unix " eol
set showmatch " show matching bracket

set noerrorbells
set novisualbell
set vb t_vb= " no bells
set modeline " show current mode
set incsearch  " do incremental search
set history=50 " keep 50 lines in history
"set textwidth=185 " column width is 185
"set wrap " wrap after 80 chars
set hlsearch   " highlight search word
set ruler

syntax on
filetype on
filetype indent on
filetype plugin on

" C-TAB and C-SHIFT-TAB cycle tabs forward and backward
" nmap <c-.> :tabnext<cr>
" imap <c-.> <c-o>:tabnext<cr>
" vmap <c-.> <c-o>:tabnext<cr>
" nmap <c-s-tab> :tabprevious<cr>
" imap <c-s-tab> <c-o>:tabprevious<cr>
" vmap <c-s-tab> <c-o>:tabprevious<cr>

" C-# switches to tab
nmap <d-1> 1gt
nmap <d-2> 2gt
nmap <d-3> 3gt
nmap <d-4> 4gt
nmap <d-5> 5gt
nmap <d-6> 6gt
nmap <d-7> 7gt
nmap <d-8> 8gt
nmap <d-9> 9gt

if has("gui_running")
  "colors molokai
  colors spring
  set guifont=Monaco:h11
  set guioptions-=T
  set guioptions-=r
  nmap <silent> <D-3> :CommandT<CR>
endif

hi Todo guifg=#FF0000 guibg=#FF7F50
hi TODO guifg=#FF0000 guibg=#FF7F50

autocmd BufWritePre *.rb :%s/\s\+$//e
autocmd BufWritePre *.c :%s/\s\+$//e
au BufRead,BufNewFile *.scss  set filetype=scss

