
"set foldmethod=syntax
set foldmethod=marker
set foldlevelstart=1
set foldnestmax=5
set foldclose=all

set nocompatible               " use vim features
set nobackup                   " no backup
set nowritebackup              " no backup during edit session

set backspace=indent,eol,start " backspace over everything

set tabstop=2     " size of a tab
set shiftwidth=2  " size for auto/smartindent
set softtabstop=2 " a tab is this size
set expandtab     " spaces not tabs
set smartindent   " indents for you
set smarttab      " tabs at start of lines
set autoindent    " always set autoindenting on

"set toolbar=tooltips

set so=7 " 7 lines when scrolling vertically
set ffs=unix " eol

set showmatch " show matching bracket

set noerrorbells
set novisualbell
set vb t_vb= " no bells
set modeline " show current mode
set incsearch  " do incremental search
set history=50 " keep 50 lines in history
"set textwidth=185 " column width is 185
"set wrap " wrap after 80 chars
set hlsearch   " highlight search word
set ruler

" set comments+=s:/**,mb:*,el:*/

syntax on

filetype on
filetype indent on
filetype plugin on

if has("gui_running")
  " colors darkblue
  " colors twilight2
  " colors zenburn
  colors robinhood
  " set guifont=Liberation\ Mono:h12
  set guifont=Monaco:h12
  " set guitablabel=%{GuiTabLabel()}
  "set guifont=Consolas:h13
endif

hi Todo guifg=Black guibg=#FF7F50
hi TODO guifg=Black guibg=#FF7F50

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

" autocmd FileType ruby set tabstop=2|set shiftwidth=2
" autocmd FileType rhtml set tabstop=2|set shiftwidth=2

map ,* :s/^\(.*\)$/\/\* \1 \*\//<CR><Esc>:nohlsearch<CR>

imap `d def <def>(   ) <CR><CR>end<UP><UP><right><right><ESC>i
imap `c class [class] <CR><CR>end<UP><UP><right><right><right><ESC>i
imap `p <%=   -%><left><left><left><left><ESC>i

" vmap sb "zdi<b><C-R>z</b><ESC>i
" ruby echo
vmap re "zdi<%= <C-R>z -%><ESC>i

autocmd BufRead * silent! %s/^M$//

